=head1 NAME

ffprobe - FFprobe media prober

=head1 SYNOPSIS

ffprobe [options] [F<input_file>]

=head1 DESCRIPTION


FFprobe gathers information from multimedia streams and prints it in
human- and machine-readable fashion.

For example it can be used to check the format of the container used
by a multimedia stream and the format and type of each media stream
contained in it.

If a filename is specified in input, ffprobe will try to open and
probe the file content. If the file cannot be opened or recognized as
a multimedia file, a positive exit code is returned.

FFprobe may be employed both as a standalone application or in
combination with a textual filter, which may perform more
sophisticated processing, e.g. statistical processing or plotting.

Options are used to list some of the formats supported by ffprobe or
for specifying which information to display, and for setting how
ffprobe will show it.

FFprobe output is designed to be easily parsable by a textual filter,
and consists of one or more sections of the form:
	
	[SECTION]
	key1=val1
	...
	keyN=valN
	[/SECTION]


Metadata tags stored in the container or in the streams are recognized
and printed in the corresponding "FORMAT" or "STREAM" section, and
are prefixed by the string "TAG:".


=head1 OPTIONS


All the numerical options, if not specified otherwise, accept in input
a string representing a number, which may contain one of the
International System number postfixes, for example 'K', 'M', 'G'.
If 'i' is appended after the postfix, powers of 2 are used instead of
powers of 10. The 'B' postfix multiplies the value for 8, and can be
appended after another postfix or used alone. This allows using for
example 'KB', 'MiB', 'G' and 'B' as postfix.

Options which do not take arguments are boolean options, and set the
corresponding value to true. They can be set to false by prefixing
with "no" the option name, for example using "-nofoo" in the
commandline will set to false the boolean option with name "foo".


=head2 Generic options


These options are shared amongst the ff* tools.


=over 4



=item B<-L>

Show license.


=item B<-h, -?, -help, --help>

Show help.


=item B<-version>

Show version.


=item B<-formats>

Show available formats.

The fields preceding the format names have the following meanings:

=over 4


=item B<D>

Decoding available

=item B<E>

Encoding available

=back



=item B<-codecs>

Show available codecs.

The fields preceding the codec names have the following meanings:

=over 4


=item B<D>

Decoding available

=item B<E>

Encoding available

=item B<V/A/S>

Video/audio/subtitle codec

=item B<S>

Codec supports slices

=item B<D>

Codec supports direct rendering

=item B<T>

Codec can handle input truncated at random locations instead of only at frame boundaries

=back



=item B<-bsfs>

Show available bitstream filters.


=item B<-protocols>

Show available protocols.


=item B<-filters>

Show available libavfilter filters.


=item B<-pix_fmts>

Show available pixel formats.


=item B<-loglevel> I<loglevel>

Set the logging level used by the library.
I<loglevel> is a number or a string containing one of the following values:

=over 4


=item B<quiet>


=item B<panic>


=item B<fatal>


=item B<error>


=item B<warning>


=item B<info>


=item B<verbose>


=item B<debug>


=back


By default the program logs to stderr, if coloring is supported by the
terminal, colors are used to mark errors and warnings. Log coloring
can be disabled setting the environment variable
B<FFMPEG_FORCE_NOCOLOR> or B<NO_COLOR>, or can be forced setting
the environment variable B<FFMPEG_FORCE_COLOR>.
The use of the environment variable B<NO_COLOR> is deprecated and
will be dropped in a following FFmpeg version.


=back



=head2 Main options



=over 4



=item B<-f> I<format>

Force format to use.


=item B<-unit>

Show the unit of the displayed values.


=item B<-prefix>

Use SI prefixes for the displayed values.
Unless the "-byte_binary_prefix" option is used all the prefixes
are decimal.


=item B<-byte_binary_prefix>

Force the use of binary prefixes for byte values.


=item B<-sexagesimal>

Use sexagesimal format HH:MM:SS.MICROSECONDS for time values.


=item B<-pretty>

Prettify the format of the displayed values, it corresponds to the
options "-unit -prefix -byte_binary_prefix -sexagesimal".


=item B<-show_format>

Show information about the container format of the input multimedia
stream.

All the container format information is printed within a section with
name "FORMAT".


=item B<-show_packets>

Show information about each packet contained in the input multimedia
stream.

The information for each single packet is printed within a dedicated
section with name "PACKET".


=item B<-show_streams>

Show information about each media stream contained in the input
multimedia stream.

Each media stream information is printed within a dedicated section
with name "STREAM".


=back


=head1 DEMUXERS


Demuxers are configured elements in FFmpeg which allow to read the
multimedia streams from a particular type of file.

When you configure your FFmpeg build, all the supported demuxers
are enabled by default. You can list all available ones using the
configure option "--list-demuxers".

You can disable all the demuxers using the configure option
"--disable-demuxers", and selectively enable a single demuxer with
the option "--enable-demuxer=I<DEMUXER>", or disable it
with the option "--disable-demuxer=I<DEMUXER>".

The option "-formats" of the ff* tools will display the list of
enabled demuxers.

The description of some of the currently available demuxers follows.


=head2 image2


Image file demuxer.

This demuxer reads from a list of image files specified by a pattern.

The pattern may contain the string "%d" or "%0I<N>d", which
specifies the position of the characters representing a sequential
number in each filename matched by the pattern. If the form
"%d0I<N>d" is used, the string representing the number in each
filename is 0-padded and I<N> is the total number of 0-padded
digits representing the number. The literal character '%' can be
specified in the pattern with the string "%%".

If the pattern contains "%d" or "%0I<N>d", the first filename of
the file list specified by the pattern must contain a number
inclusively contained between 0 and 4, all the following numbers must
be sequential. This limitation may be hopefully fixed.

The pattern may contain a suffix which is used to automatically
determine the format of the images contained in the files.

For example the pattern "img-%03d.bmp" will match a sequence of
filenames of the form F<img-001.bmp>, F<img-002.bmp>, ...,
F<img-010.bmp>, etc.; the pattern "i%%m%%g-%d.jpg" will match a
sequence of filenames of the form F<i%m%g-1.jpg>,
F<i%m%g-2.jpg>, ..., F<i%m%g-10.jpg>, etc.

The size, the pixel format, and the format of each image must be the
same for all the files in the sequence.

The following example shows how to use F<ffmpeg> for creating a
video from the images in the file sequence F<img-001.jpeg>,
F<img-002.jpeg>, ..., assuming an input framerate of 10 frames per
second:
	
	ffmpeg -r 10 -f image2 -i 'img-%03d.jpeg' out.avi


Note that the pattern must not necessarily contain "%d" or
"%0I<N>d", for example to convert a single image file
F<img.jpeg> you can employ the command:
	
	ffmpeg -f image2 -i img.jpeg img.png



=head1 MUXERS


Muxers are configured elements in FFmpeg which allow writing
multimedia streams to a particular type of file.

When you configure your FFmpeg build, all the supported muxers
are enabled by default. You can list all available muxers using the
configure option C<--list-muxers>.

You can disable all the muxers with the configure option
C<--disable-muxers> and selectively enable / disable single muxers
with the options C<--enable-muxer=I<MUXER>> /
C<--disable-muxer=I<MUXER>>.

The option C<-formats> of the ff* tools will display the list of
enabled muxers.

A description of some of the currently available muxers follows.



=head2 crc


CRC (Cyclic Redundancy Check) testing format.

This muxer computes and prints the Adler-32 CRC of all the input audio
and video frames. By default audio frames are converted to signed
16-bit raw audio and video frames to raw video before computing the
CRC.

The output of the muxer consists of a single line of the form:
CRC=0xI<CRC>, where I<CRC> is a hexadecimal number 0-padded to
8 digits containing the CRC for all the decoded input frames.

For example to compute the CRC of the input, and store it in the file
F<out.crc>:
	
	ffmpeg -i INPUT -f crc out.crc


You can print the CRC to stdout with the command:
	
	ffmpeg -i INPUT -f crc -


You can select the output format of each frame with F<ffmpeg> by
specifying the audio and video codec and format. For example to
compute the CRC of the input audio converted to PCM unsigned 8-bit
and the input video converted to MPEG-2 video, use the command:
	
	ffmpeg -i INPUT -acodec pcm_u8 -vcodec mpeg2video -f crc -


See also the C<framecrc> muxer.



=head2 framecrc


Per-frame CRC (Cyclic Redundancy Check) testing format.

This muxer computes and prints the Adler-32 CRC for each decoded audio
and video frame. By default audio frames are converted to signed
16-bit raw audio and video frames to raw video before computing the
CRC.

The output of the muxer consists of a line for each audio and video
frame of the form: I<stream_index>, I<frame_dts>,
I<frame_size>, 0xI<CRC>, where I<CRC> is a hexadecimal
number 0-padded to 8 digits containing the CRC of the decoded frame.

For example to compute the CRC of each decoded frame in the input, and
store it in the file F<out.crc>:
	
	ffmpeg -i INPUT -f framecrc out.crc


You can print the CRC of each decoded frame to stdout with the command:
	
	ffmpeg -i INPUT -f framecrc -


You can select the output format of each frame with F<ffmpeg> by
specifying the audio and video codec and format. For example, to
compute the CRC of each decoded input audio frame converted to PCM
unsigned 8-bit and of each decoded input video frame converted to
MPEG-2 video, use the command:
	
	ffmpeg -i INPUT -acodec pcm_u8 -vcodec mpeg2video -f framecrc -


See also the C<crc> muxer.


=head2 image2


Image file muxer.

The image file muxer writes video frames to image files.

The output filenames are specified by a pattern, which can be used to
produce sequentially numbered series of files.
The pattern may contain the string "%d" or "%0I<N>d", this string
specifies the position of the characters representing a numbering in
the filenames. If the form "%0I<N>d" is used, the string
representing the number in each filename is 0-padded to I<N>
digits. The literal character '%' can be specified in the pattern with
the string "%%".

If the pattern contains "%d" or "%0I<N>d", the first filename of
the file list specified will contain the number 1, all the following
numbers will be sequential.

The pattern may contain a suffix which is used to automatically
determine the format of the image files to write.

For example the pattern "img-%03d.bmp" will specify a sequence of
filenames of the form F<img-001.bmp>, F<img-002.bmp>, ...,
F<img-010.bmp>, etc.
The pattern "img%%-%d.jpg" will specify a sequence of filenames of the
form F<img%-1.jpg>, F<img%-2.jpg>, ..., F<img%-10.jpg>,
etc.

The following example shows how to use F<ffmpeg> for creating a
sequence of files F<img-001.jpeg>, F<img-002.jpeg>, ...,
taking one image every second from the input video:
	
	ffmpeg -i in.avi -r 1 -f image2 'img-%03d.jpeg'


Note that with F<ffmpeg>, if the format is not specified with the
C<-f> option and the output filename specifies an image file
format, the image2 muxer is automatically selected, so the previous
command can be written as:
	
	ffmpeg -i in.avi -r 1 'img-%03d.jpeg'


Note also that the pattern must not necessarily contain "%d" or
"%0I<N>d", for example to create a single image file
F<img.jpeg> from the input video you can employ the command:
	
	ffmpeg -i in.avi -f image2 -vframes 1 img.jpeg


The image muxer supports the .Y.U.V image file format. This format is
special in that that each image frame consists of three files, for
each of the YUV420P components. To read or write this image file format,
specify the name of the '.Y' file. The muxer will automatically open the
'.U' and '.V' files as required.


=head2 mpegts


MPEG transport stream muxer.

This muxer implements ISO 13818-1 and part of ETSI EN 300 468.

The muxer options are:


=over 4


=item B<-mpegts_original_network_id> I<number>

Set the original_network_id (default 0x0001). This is unique identifier
of a network in DVB. Its main use is in the unique identification of a
service through the path Original_Network_ID, Transport_Stream_ID.

=item B<-mpegts_transport_stream_id> I<number>

Set the transport_stream_id (default 0x0001). This identifies a
transponder in DVB.

=item B<-mpegts_service_id> I<number>

Set the service_id (default 0x0001) also known as program in DVB.

=item B<-mpegts_pmt_start_pid> I<number>

Set the first PID for PMT (default 0x1000, max 0x1f00).

=item B<-mpegts_start_pid> I<number>

Set the first PID for data packets (default 0x0100, max 0x0f00).

=back


The recognized metadata settings in mpegts muxer are C<service_provider>
and C<service_name>. If they are not set the default for
C<service_provider> is "FFmpeg" and the default for
C<service_name> is "Service01".

	
	ffmpeg -i file.mpg -acodec copy -vcodec copy \
	     -mpegts_original_network_id 0x1122 \
	     -mpegts_transport_stream_id 0x3344 \
	     -mpegts_service_id 0x5566 \
	     -mpegts_pmt_start_pid 0x1500 \
	     -mpegts_start_pid 0x150 \
	     -metadata service_provider="Some provider" \
	     -metadata service_name="Some Channel" \
	     -y out.ts



=head2 null


Null muxer.

This muxer does not generate any output file, it is mainly useful for
testing or benchmarking purposes.

For example to benchmark decoding with F<ffmpeg> you can use the
command:
	
	ffmpeg -benchmark -i INPUT -f null out.null


Note that the above command does not read or write the F<out.null>
file, but specifying the output file is required by the F<ffmpeg>
syntax.

Alternatively you can write the command as:
	
	ffmpeg -benchmark -i INPUT -f null -



=head1 PROTOCOLS


Protocols are configured elements in FFmpeg which allow to access
resources which require the use of a particular protocol.

When you configure your FFmpeg build, all the supported protocols are
enabled by default. You can list all available ones using the
configure option "--list-protocols".

You can disable all the protocols using the configure option
"--disable-protocols", and selectively enable a protocol using the
option "--enable-protocol=I<PROTOCOL>", or you can disable a
particular protocol using the option
"--disable-protocol=I<PROTOCOL>".

The option "-protocols" of the ff* tools will display the list of
supported protocols.

A description of the currently available protocols follows.


=head2 applehttp


Read Apple HTTP Live Streaming compliant segmented stream as
a uniform one. The M3U8 playlists describing the segments can be
remote HTTP resources or local files, accessed using the standard
file protocol.
HTTP is default, specific protocol can be declared by specifying
"+I<proto>" after the applehttp URI scheme name, where I<proto>
is either "file" or "http".

	
	applehttp://host/path/to/remote/resource.m3u8
	applehttp+http://host/path/to/remote/resource.m3u8
	applehttp+file://path/to/local/resource.m3u8



=head2 concat


Physical concatenation protocol.

Allow to read and seek from many resource in sequence as if they were
a unique resource.

A URL accepted by this protocol has the syntax:
	
	concat:<URL1>|<URL2>|...|<URLN>


where I<URL1>, I<URL2>, ..., I<URLN> are the urls of the
resource to be concatenated, each one possibly specifying a distinct
protocol.

For example to read a sequence of files F<split1.mpeg>,
F<split2.mpeg>, F<split3.mpeg> with F<ffplay> use the
command:
	
	ffplay concat:split1.mpeg\|split2.mpeg\|split3.mpeg


Note that you may need to escape the character "|" which is special for
many shells.


=head2 file


File access protocol.

Allow to read from or read to a file.

For example to read from a file F<input.mpeg> with F<ffmpeg>
use the command:
	
	ffmpeg -i file:input.mpeg output.mpeg


The ff* tools default to the file protocol, that is a resource
specified with the name "FILE.mpeg" is interpreted as the URL
"file:FILE.mpeg".


=head2 gopher


Gopher protocol.


=head2 http


HTTP (Hyper Text Transfer Protocol).


=head2 mmst


MMS (Microsoft Media Server) protocol over TCP.


=head2 mmsh


MMS (Microsoft Media Server) protocol over HTTP.

The required syntax is:
	
	mmsh://<server>[:<port>][/<app>][/<playpath>]



=head2 md5


MD5 output protocol.

Computes the MD5 hash of the data to be written, and on close writes
this to the designated output or stdout if none is specified. It can
be used to test muxers without writing an actual file.

Some examples follow.
	
	# Write the MD5 hash of the encoded AVI file to the file output.avi.md5.
	ffmpeg -i input.flv -f avi -y md5:output.avi.md5
	
	# Write the MD5 hash of the encoded AVI file to stdout.
	ffmpeg -i input.flv -f avi -y md5:


Note that some formats (typically MOV) require the output protocol to
be seekable, so they will fail with the MD5 output protocol.


=head2 pipe


UNIX pipe access protocol.

Allow to read and write from UNIX pipes.

The accepted syntax is:
	
	pipe:[<number>]


I<number> is the number corresponding to the file descriptor of the
pipe (e.g. 0 for stdin, 1 for stdout, 2 for stderr).  If I<number>
is not specified, by default the stdout file descriptor will be used
for writing, stdin for reading.

For example to read from stdin with F<ffmpeg>:
	
	cat test.wav | ffmpeg -i pipe:0
	# ...this is the same as...
	cat test.wav | ffmpeg -i pipe:


For writing to stdout with F<ffmpeg>:
	
	ffmpeg -i test.wav -f avi pipe:1 | cat > test.avi
	# ...this is the same as...
	ffmpeg -i test.wav -f avi pipe: | cat > test.avi


Note that some formats (typically MOV), require the output protocol to
be seekable, so they will fail with the pipe output protocol.


=head2 rtmp


Real-Time Messaging Protocol.

The Real-Time Messaging Protocol (RTMP) is used for streaming multime‐
dia content across a TCP/IP network.

The required syntax is:
	
	rtmp://<server>[:<port>][/<app>][/<playpath>]


The accepted parameters are:

=over 4



=item B<server>

The address of the RTMP server.


=item B<port>

The number of the TCP port to use (by default is 1935).


=item B<app>

It is the name of the application to access. It usually corresponds to
the path where the application is installed on the RTMP server
(e.g. F</ondemand/>, F</flash/live/>, etc.).


=item B<playpath>

It is the path or name of the resource to play with reference to the
application specified in I<app>, may be prefixed by "mp4:".


=back


For example to read with F<ffplay> a multimedia resource named
"sample" from the application "vod" from an RTMP server "myserver":
	
	ffplay rtmp://myserver/vod/sample



=head2 rtmp, rtmpe, rtmps, rtmpt, rtmpte


Real-Time Messaging Protocol and its variants supported through
librtmp.

Requires the presence of the librtmp headers and library during
configuration. You need to explicitely configure the build with
"--enable-librtmp". If enabled this will replace the native RTMP
protocol.

This protocol provides most client functions and a few server
functions needed to support RTMP, RTMP tunneled in HTTP (RTMPT),
encrypted RTMP (RTMPE), RTMP over SSL/TLS (RTMPS) and tunneled
variants of these encrypted types (RTMPTE, RTMPTS).

The required syntax is:
	
	<rtmp_proto>://<server>[:<port>][/<app>][/<playpath>] <options>


where I<rtmp_proto> is one of the strings "rtmp", "rtmpt", "rtmpe",
"rtmps", "rtmpte", "rtmpts" corresponding to each RTMP variant, and
I<server>, I<port>, I<app> and I<playpath> have the same
meaning as specified for the RTMP native protocol.
I<options> contains a list of space-separated options of the form
I<key>=I<val>.

See the librtmp manual page (man 3 librtmp) for more information.

For example, to stream a file in real-time to an RTMP server using
F<ffmpeg>:
	
	ffmpeg -re -i myfile -f flv rtmp://myserver/live/mystream


To play the same stream using F<ffplay>:
	
	ffplay "rtmp://myserver/live/mystream live=1"



=head2 rtp


Real-Time Protocol.


=head2 rtsp


RTSP is not technically a protocol handler in libavformat, it is a demuxer
and muxer. The demuxer supports both normal RTSP (with data transferred
over RTP; this is used by e.g. Apple and Microsoft) and Real-RTSP (with
data transferred over RDT).

The muxer can be used to send a stream using RTSP ANNOUNCE to a server
supporting it (currently Darwin Streaming Server and Mischa Spiegelmock's
RTSP server, E<lt>B<http://github.com/revmischa/rtsp-server>E<gt>).

The required syntax for a RTSP url is:
	
	rtsp://<hostname>[:<port>]/<path>[?<options>]


I<options> is a C<&>-separated list. The following options
are supported:


=over 4



=item B<udp>

Use UDP as lower transport protocol.


=item B<tcp>

Use TCP (interleaving within the RTSP control channel) as lower
transport protocol.


=item B<multicast>

Use UDP multicast as lower transport protocol.


=item B<http>

Use HTTP tunneling as lower transport protocol, which is useful for
passing proxies.


=item B<filter_src>

Accept packets only from negotiated peer address and port.

=back


Multiple lower transport protocols may be specified, in that case they are
tried one at a time (if the setup of one fails, the next one is tried).
For the muxer, only the C<tcp> and C<udp> options are supported.

When receiving data over UDP, the demuxer tries to reorder received packets
(since they may arrive out of order, or packets may get lost totally). In
order for this to be enabled, a maximum delay must be specified in the
C<max_delay> field of AVFormatContext.

When watching multi-bitrate Real-RTSP streams with F<ffplay>, the
streams to display can be chosen with C<-vst> I<n> and
C<-ast> I<n> for video and audio respectively, and can be switched
on the fly by pressing C<v> and C<a>.

Example command lines:

To watch a stream over UDP, with a max reordering delay of 0.5 seconds:

	
	ffplay -max_delay 500000 rtsp://server/video.mp4?udp


To watch a stream tunneled over HTTP:

	
	ffplay rtsp://server/video.mp4?http


To send a stream in realtime to a RTSP server, for others to watch:

	
	ffmpeg -re -i <input> -f rtsp -muxdelay 0.1 rtsp://server/live.sdp



=head2 sap


Session Announcement Protocol (RFC 2974). This is not technically a
protocol handler in libavformat, it is a muxer and demuxer.
It is used for signalling of RTP streams, by announcing the SDP for the
streams regularly on a separate port.


=head3 Muxer


The syntax for a SAP url given to the muxer is:
	
	sap://<destination>[:<port>][?<options>]


The RTP packets are sent to I<destination> on port I<port>,
or to port 5004 if no port is specified.
I<options> is a C<&>-separated list. The following options
are supported:


=over 4



=item B<announce_addr=>I<address>

Specify the destination IP address for sending the announcements to.
If omitted, the announcements are sent to the commonly used SAP
announcement multicast address 224.2.127.254 (sap.mcast.net), or
ff0e::2:7ffe if I<destination> is an IPv6 address.


=item B<announce_port=>I<port>

Specify the port to send the announcements on, defaults to
9875 if not specified.


=item B<ttl=>I<ttl>

Specify the time to live value for the announcements and RTP packets,
defaults to 255.


=item B<same_port=>I<0|1>

If set to 1, send all RTP streams on the same port pair. If zero (the
default), all streams are sent on unique ports, with each stream on a
port 2 numbers higher than the previous.
VLC/Live555 requires this to be set to 1, to be able to receive the stream.
The RTP stack in libavformat for receiving requires all streams to be sent
on unique ports.

=back


Example command lines follow.

To broadcast a stream on the local subnet, for watching in VLC:

	
	ffmpeg -re -i <input> -f sap sap://224.0.0.255?same_port=1


Similarly, for watching in ffplay:

	
	ffmpeg -re -i <input> -f sap sap://224.0.0.255


And for watching in ffplay, over IPv6:

	
	ffmpeg -re -i <input> -f sap sap://[ff0e::1:2:3:4]



=head3 Demuxer


The syntax for a SAP url given to the demuxer is:
	
	sap://[<address>][:<port>]


I<address> is the multicast address to listen for announcements on,
if omitted, the default 224.2.127.254 (sap.mcast.net) is used. I<port>
is the port that is listened on, 9875 if omitted.

The demuxers listens for announcements on the given address and port.
Once an announcement is received, it tries to receive that particular stream.

Example command lines follow.

To play back the first stream announced on the normal SAP multicast address:

	
	ffplay sap://


To play back the first stream announced on one the default IPv6 SAP multicast address:

	
	ffplay sap://[ff0e::2:7ffe]



=head2 tcp


Trasmission Control Protocol.

The required syntax for a TCP url is:
	
	tcp://<hostname>:<port>[?<options>]



=over 4



=item B<listen>

Listen for an incoming connection

	
	ffmpeg -i <input> -f <format> tcp://<hostname>:<port>?listen
	ffplay tcp://<hostname>:<port>



=back



=head2 udp


User Datagram Protocol.

The required syntax for a UDP url is:
	
	udp://<hostname>:<port>[?<options>]


I<options> contains a list of &-seperated options of the form I<key>=I<val>.
Follow the list of supported options.


=over 4



=item B<buffer_size=>I<size>

set the UDP buffer size in bytes


=item B<localport=>I<port>

override the local UDP port to bind with


=item B<pkt_size=>I<size>

set the size in bytes of UDP packets


=item B<reuse=>I<1|0>

explicitly allow or disallow reusing UDP sockets


=item B<ttl=>I<ttl>

set the time to live value (for multicast only)


=item B<connect=>I<1|0>

Initialize the UDP socket with C<connect()>. In this case, the
destination address can't be changed with ff_udp_set_remote_url later.
If the destination address isn't known at the start, this option can
be specified in ff_udp_set_remote_url, too.
This allows finding out the source address for the packets with getsockname,
and makes writes return with AVERROR(ECONNREFUSED) if "destination
unreachable" is received.
For receiving, this gives the benefit of only receiving packets from
the specified peer address/port.

=back


Some usage examples of the udp protocol with F<ffmpeg> follow.

To stream over UDP to a remote endpoint:
	
	ffmpeg -i <input> -f <format> udp://<hostname>:<port>


To stream in mpegts format over UDP using 188 sized UDP packets, using a large input buffer:
	
	ffmpeg -i <input> -f mpegts udp://<hostname>:<port>?pkt_size=188&buffer_size=65535


To receive over UDP from a remote endpoint:
	
	ffmpeg -i udp://[<multicast-address>]:<port>



=head1 INPUT DEVICES


Input devices are configured elements in FFmpeg which allow to access
the data coming from a multimedia device attached to your system.

When you configure your FFmpeg build, all the supported input devices
are enabled by default. You can list all available ones using the
configure option "--list-indevs".

You can disable all the input devices using the configure option
"--disable-indevs", and selectively enable an input device using the
option "--enable-indev=I<INDEV>", or you can disable a particular
input device using the option "--disable-indev=I<INDEV>".

The option "-formats" of the ff* tools will display the list of
supported input devices (amongst the demuxers).

A description of the currently available input devices follows.


=head2 alsa


ALSA (Advanced Linux Sound Architecture) input device.

To enable this input device during configuration you need libasound
installed on your system.

This device allows capturing from an ALSA device. The name of the
device to capture has to be an ALSA card identifier.

An ALSA identifier has the syntax:
	
	hw:<CARD>[,<DEV>[,<SUBDEV>]]


where the I<DEV> and I<SUBDEV> components are optional.

The three arguments (in order: I<CARD>,I<DEV>,I<SUBDEV>)
specify card number or identifier, device number and subdevice number
(-1 means any).

To see the list of cards currently recognized by your system check the
files F</proc/asound/cards> and F</proc/asound/devices>.

For example to capture with F<ffmpeg> from an ALSA device with
card id 0, you may run the command:
	
	ffmpeg -f alsa -i hw:0 alsaout.wav


For more information see:
E<lt>B<http://www.alsa-project.org/alsa-doc/alsa-lib/pcm.html>E<gt>


=head2 bktr


BSD video input device.


=head2 dv1394


Linux DV 1394 input device.


=head2 fbdev


Linux framebuffer input device.

The Linux framebuffer is a graphic hardware-independent abstraction
layer to show graphics on a computer monitor, typically on the
console. It is accessed through a file device node, usually
F</dev/fb0>.

For more detailed information read the file
Documentation/fb/framebuffer.txt included in the Linux source tree.

To record from the framebuffer device F</dev/fb0> with
F<ffmpeg>:
	
	ffmpeg -f fbdev -r 10 -i /dev/fb0 out.avi


You can take a single screenshot image with the command:
	
	ffmpeg -f fbdev -vframes 1 -r 1 -i /dev/fb0 screenshot.jpeg


See also E<lt>B<http://linux-fbdev.sourceforge.net/>E<gt>, and fbset(1).


=head2 jack


JACK input device.

To enable this input device during configuration you need libjack
installed on your system.

A JACK input device creates one or more JACK writable clients, one for
each audio channel, with name I<client_name>:input_I<N>, where
I<client_name> is the name provided by the application, and I<N>
is a number which identifies the channel.
Each writable client will send the acquired data to the FFmpeg input
device.

Once you have created one or more JACK readable clients, you need to
connect them to one or more JACK writable clients.

To connect or disconnect JACK clients you can use the
F<jack_connect> and F<jack_disconnect> programs, or do it
through a graphical interface, for example with F<qjackctl>.

To list the JACK clients and their properties you can invoke the command
F<jack_lsp>.

Follows an example which shows how to capture a JACK readable client
with F<ffmpeg>.
	
	# Create a JACK writable client with name "ffmpeg".
	$ ffmpeg -f jack -i ffmpeg -y out.wav
	
	# Start the sample jack_metro readable client.
	$ jack_metro -b 120 -d 0.2 -f 4000
	
	# List the current JACK clients.
	$ jack_lsp -c
	system:capture_1
	system:capture_2
	system:playback_1
	system:playback_2
	ffmpeg:input_1
	metro:120_bpm
	
	# Connect metro to the ffmpeg writable client.
	$ jack_connect metro:120_bpm ffmpeg:input_1


For more information read:
E<lt>B<http://jackaudio.org/>E<gt>


=head2 libdc1394


IIDC1394 input device, based on libdc1394 and libraw1394.


=head2 oss


Open Sound System input device.

The filename to provide to the input device is the device node
representing the OSS input device, and is usually set to
F</dev/dsp>.

For example to grab from F</dev/dsp> using F<ffmpeg> use the
command:
	
	ffmpeg -f oss -i /dev/dsp /tmp/oss.wav


For more information about OSS see:
E<lt>B<http://manuals.opensound.com/usersguide/dsp.html>E<gt>


=head2 sndio


sndio input device.

To enable this input device during configuration you need libsndio
installed on your system.

The filename to provide to the input device is the device node
representing the sndio input device, and is usually set to
F</dev/audio0>.

For example to grab from F</dev/audio0> using F<ffmpeg> use the
command:
	
	ffmpeg -f sndio -i /dev/audio0 /tmp/oss.wav



=head2 video4linux and video4linux2


Video4Linux and Video4Linux2 input video devices.

The name of the device to grab is a file device node, usually Linux
systems tend to automatically create such nodes when the device
(e.g. an USB webcam) is plugged into the system, and has a name of the
kind F</dev/videoI<N>>, where I<N> is a number associated to
the device.

Video4Linux and Video4Linux2 devices only support a limited set of
I<width>xI<height> sizes and framerates. You can check which are
supported for example with the command F<dov4l> for Video4Linux
devices and the command F<v4l-info> for Video4Linux2 devices.

If the size for the device is set to 0x0, the input device will
try to autodetect the size to use.
Only for the video4linux2 device, if the frame rate is set to 0/0 the
input device will use the frame rate value already set in the driver.

Video4Linux support is deprecated since Linux 2.6.30, and will be
dropped in later versions.

Follow some usage examples of the video4linux devices with the ff*
tools.
	
	# Grab and show the input of a video4linux device, frame rate is set
	# to the default of 25/1.
	ffplay -s 320x240 -f video4linux /dev/video0
	
	# Grab and show the input of a video4linux2 device, autoadjust size.
	ffplay -f video4linux2 /dev/video0
	
	# Grab and record the input of a video4linux2 device, autoadjust size,
	# frame rate value defaults to 0/0 so it is read from the video4linux2
	# driver.
	ffmpeg -f video4linux2 -i /dev/video0 out.mpeg



=head2 vfwcap


VfW (Video for Windows) capture input device.

The filename passed as input is the capture driver number, ranging from
0 to 9. You may use "list" as filename to print a list of drivers. Any
other filename will be interpreted as device number 0.


=head2 x11grab


X11 video input device.

This device allows to capture a region of an X11 display.

The filename passed as input has the syntax:
	
	[<hostname>]:<display_number>.<screen_number>[+<x_offset>,<y_offset>]


I<hostname>:I<display_number>.I<screen_number> specifies the
X11 display name of the screen to grab from. I<hostname> can be
ommitted, and defaults to "localhost". The environment variable
B<DISPLAY> contains the default display name.

I<x_offset> and I<y_offset> specify the offsets of the grabbed
area with respect to the top-left border of the X11 screen. They
default to 0.

Check the X11 documentation (e.g. man X) for more detailed information.

Use the F<dpyinfo> program for getting basic information about the
properties of your X11 display (e.g. grep for "name" or "dimensions").

For example to grab from F<:0.0> using F<ffmpeg>:
	
	ffmpeg -f x11grab -r 25 -s cif -i :0.0 out.mpg
	
	# Grab at position 10,20.
	ffmpeg -f x11grab -25 -s cif -i :0.0+10,20 out.mpg



=head1 SEE ALSO

ffmpeg(1), ffplay(1), ffserver(1) and the FFmpeg HTML documentation

=head1 AUTHORS

The FFmpeg developers

